### ISSUE TITLE
Parentheses around sizeof operand

### ISSUE THREAD

**Issue by castan3** [RobertGrancsa/checker#1]
The style checker currently enforces the use of `sizeof(p)` as opposed to `sizeof p`. Is this behavior intended?

As `sizeof` is a unary operator, the situation is analogous to using `-(p)` over `-p`. Enforcing parentheses where they can be avoided may give the impression that `sizeof(p)` is syntactically similar to the function call `foo(p)`. However, in a function call, parentheses designate the function call operator, as opposed to a paranthesized expression as in the case of `sizeof`.

To illustrate, consider the expression `sizeof(0) ["iocla"]`.

**Comment by RobertGrancsa** [comment]
We are using the [linux kernel coding style checker](https://docs.kernel.org/dev-tools/checkpatch.html), which enforces this way of using parentheses. So at least for now, we will be using this type of coding style
